### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by FelipeDeFi** [Solana0x/nodepay#4]
I've been having this kind of issue. Any idea? TVM

:~/nodepay2/nodepay$ python3 node.py 
Traceback (most recent call last):
  File "/home/***/node.py", line 170, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/***/node.py", line 147, in main
    done, pending = await asyncio.wait(tasks.keys(), return_when=asyncio.FIRST_COMPLETED)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 368, in wait
    raise ValueError('Set of coroutines/Futures is empty.')
ValueError: Set of coroutines/Futures is empty.

**Comment by Solana0x** [comment]
You didnt added the required number of proxies please add more proxies and formate is 

http://username:pass@ip:port !
